name: mapsindoors_googlemaps_android
description: Android implementation of the mapsindoors plugin using the Google Maps platform
version: 4.5.1
repository: https://github.com/MapsPeople/mapsindoors_flutter_googlemaps_android
homepage: https://www.mapsindoors.com/

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: mapsindoors
    platforms:
      android:
        package: com.mapspeople.mapsindoors.core
        pluginClass: MapsindoorsPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.15
  mapsindoors_platform_interface: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0